### ISSUE TITLE
Sort out thank you messages that get sent out

### ISSUE THREAD

**Issue by melissajanefisher** [testingstories/testingstories#26]
![image](https://user-images.githubusercontent.com/77445691/113290677-e57ad600-92e9-11eb-82cf-8ef4644818a3.png)

**Comment by andreajensenfl** [comment]
Thank you for choosing **Testing Stories**, stories from and about testers. We hope you will enjoy reading our stories.  The money from the purchases of this book will be donated, so thank you for supporting our project and the community!

**Comment by melissajanefisher** [comment]
pasted this in leanpub :)
