### ISSUE TITLE
Work on tester of the day

### ISSUE THREAD

**Issue by melissajanefisher** [testingstories/testingstories#37]
block quote is weird and blue like, but not block quote formatting

**Comment by melissajanefisher** [comment]
I've removed the blue colour and changed it to black.  I've put quotes around the text.

also, changed the formatting so all the current volunteers show on one page.

**Comment by dowenb** [comment]
Thanks @melissajanefisher , I've made some further edits to try and get a "block quote" style, although disappointingly there isn't a "block quotes" style in Google Docs, so I've had to use italics and indent. I've also changes the page breaks. Looks alright to me now in the Doc, will see how it exports!
