### ISSUE TITLE
Reviewing the PR

### ISSUE THREAD

**Issue by devonps** [testingstories/testingstories#7]
How many reviewers are needed to merge the PR?

**Comment by haroon-sheikh** [comment]
Shall we say at least 2? What do you think @melissafisher?

**Comment by devonps** [comment]
And would that include spelling, grammar, and structure OR just structure of the story?
Obviously we could leave that to the author, which isn't a bad thing, and if so what would be the purpose of the review?

**Comment by melissajanefisher** [comment]
As a reviewer, we want to enable the author to write the best version of the story they can.

Any grammar, spelling and also, if anything is unclear or perhaps they can expand.

**Comment by devonps** [comment]
Happy to close this now - agree?

**Comment by melissajanefisher** [comment]
Yep, let's close.
